# Generated by Django 4.2.4 on 2023-09-01 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fruit", "0003_fruittable_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="fruitimg",
            name="fruittable",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fruit.fruittable",
            ),
        ),
    ]
