# Generated by Django 4.2.2 on 2023-09-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0005_fruitsugar_fruittable'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruittable',
            name='regdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
